#!/usr/bin/env sh

# Skip if commitlint is not installed
if ! command -v npx >/dev/null 2>&1; then
  exit 0
fi

# Check if commitlint is available
npx --no -- commitlint --version >/dev/null 2>&1 || exit 0

# Run commitlint
npx --no -- commitlint --edit "$1"

