#!/usr/bin/env sh

# Skip if lint-staged is not installed
if ! command -v npx >/dev/null 2>&1; then
  exit 0
fi

# Check if lint-staged is available
npx --no -- lint-staged --version >/dev/null 2>&1 || exit 0

# Run lint-staged
npx --no -- lint-staged

